-- The official PostgreSQL image creates platform_master_db and platform_user
-- from POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD. This platform uses
-- that single shared database, so no additional roles or databases are needed.
