bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
supervised no
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
appendfilename "appendonly.aof"
save 900 1
save 300 10
save 60 10000
io-threads 4
io-threads-do-reads yes
