server:
  port: 8084
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:platform_master_db}
    username: ${DB_USERNAME:platform_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: accounts
  flyway:
    enabled: true
    default-schema: accounts
    schemas: accounts
    create-schemas: true
    locations: classpath:db/migration
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:default-jwt-secret}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
