spring:
  profiles: uat
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/platform_account_db
    username: ${DB_USERNAME:platform_account_user}
    password: ${DB_PASSWORD:platform_account_password}
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:uat-jwt-secret}
