spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_payment_db
    username: platform_payment_user
    password: platform_payment_password
security:
  jwt:
    secret: dev-jwt-secret
